### ISSUE TITLE
Needs to be completed

### ISSUE THREAD

**Issue by aviflombaum** [learn-co-curriculum/ttt-10-current-player#1]
Outline here https://github.com/learn-co-curriculum/ttt-10-current-player/blob/solution/README.md

**Comment by AnnJohn** [comment]
@aviflombaum setting a deadline of today, 9/11/15 for this.

**Comment by aviflombaum** [comment]
assigning to sophine, deadline of monday 9/14 is fine

**Comment by aviflombaum** [comment]
reviewing
