### ISSUE TITLE
Nitrous IDE not working 

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/ttt-10-current-player#11]
Error message: 

Whoops! There was a problem opening this lab.

Failed to login via SSH. Have you added learn.co's public key to your Nitrous container?

**Comment by AnnJohn** [comment]
Hi @trrybck thanks for raising this issue. Also since it looks like this is something you need to have addressed away, please use the "Ask a Question" function on Learn and someone from our instructor support team will get back to you right away.
