### ISSUE TITLE
Ternary Operator should be reviewed

### ISSUE THREAD

**Issue by thegands** [learn-co-curriculum/ttt-10-current-player#15]
The bonus at the bottom of the readme suggests reworking an if/else statement using a ternary operator. Since ternary operators were not covered in previous material the readme should include a quick review of ternary operators or a link to [ruby documentation](http://ruby-doc.org/core-2.2.0/doc/syntax/control_expressions_rdoc.html#label-Ternary+if).

**Comment by AnnJohn** [comment]
thanks @thegands!  Could you actually link again to the Ruby docs. The one above doesn't link correctly. We'll update the lesson with the link.

**Comment by thegands** [comment]
i cant figure out what is wrong with the link, it seems to be working for me :(

the same link for ruby 2.3.0: http://ruby-doc.org/core-2.3.0//doc/syntax/control_expressions_rdoc.html#label-Ternary+if

**Comment by AnnJohn** [comment]
Awesome, that link works. I'm going to close this issue and update the Readme with it. Thanks again!

**Comment by thegands** [comment]
that's great, thank you! I love how everyone is able to contribute and it's wonderful being able to see improvements from your own contributions!

**Comment by AnnJohn** [comment]
Thank you again @thegands. We definitely believe that learning is also about creating, and the ability to create and contribute to your own and other people's learning is one of the reasons why we built Learn this way.
